export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
export const ADD_PRODUCT = "ADD_PRODUCT";
export const ADD_PRODUCT_FAIL = "ADD_PRODUCT_FAIL";
export const ADD_IMAGE = "ADD_IMAGE";
export const ADD_IMAGE_FAIL = "ADD_IMAGE_FAIL";
export const GET_SELLER_PRODUCTS = "GET_SELLER_PRODUCTS";

// Cart Types
export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const GET_PURCHASED_PRODUCTS = "GET_PURCHASED_PRODUCTS";
// Product
export const BUY_PRODUCT = "BUY_PRODUCT";
export const BUY_PRODUCT_FAIL = "BUY_PRODUCT_FAIL";
export const GET_ALL_PRODUCTS = "GET_ALL_PRODUCTS";
export const GET_SINGLE_PRODUCT = "GET_SINGLE_PRODUCT";
export const GET_PRODUCTS_BY_CATEGORY = "GET_PRODUCTS_BY_CATEGORY";
// Retailer Image
export const UPDATE_IMAGE = "UPDATE_IMAGE";
export const UPDATE_PROFILE = "UPDATE_PROFILE";
